/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cloud.glb
Author: Jiří Kuba (https://sketchfab.com/kuba.jirka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-852ae741a60b44ec886fbf34bbd058f8
Title: Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cloud.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cloud_0.geometry} material={materials.CloudMaterial} scale={0.86} />
      </group>
    </group>
  )
}

useGLTF.preload('/cloud.glb')
